/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PollIndexRouteImport } from './routes/poll/index'
import { Route as PollNewRouteImport } from './routes/poll/new'
import { Route as PollIdIndexRouteImport } from './routes/poll/$id/index'
import { Route as PollIdAnalyticsRouteImport } from './routes/poll/$id/analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollIndexRoute = PollIndexRouteImport.update({
  id: '/poll/',
  path: '/poll/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollNewRoute = PollNewRouteImport.update({
  id: '/poll/new',
  path: '/poll/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PollIdIndexRoute = PollIdIndexRouteImport.update({
  id: '/poll/$id/',
  path: '/poll/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollIdAnalyticsRoute = PollIdAnalyticsRouteImport.update({
  id: '/poll/$id/analytics',
  path: '/poll/$id/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/poll/new': typeof PollNewRoute
  '/poll/': typeof PollIndexRoute
  '/poll/$id/analytics': typeof PollIdAnalyticsRoute
  '/poll/$id/': typeof PollIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/poll/new': typeof PollNewRoute
  '/poll': typeof PollIndexRoute
  '/poll/$id/analytics': typeof PollIdAnalyticsRoute
  '/poll/$id': typeof PollIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/poll/new': typeof PollNewRoute
  '/poll/': typeof PollIndexRoute
  '/poll/$id/analytics': typeof PollIdAnalyticsRoute
  '/poll/$id/': typeof PollIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/poll/new'
    | '/poll/'
    | '/poll/$id/analytics'
    | '/poll/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/poll/new'
    | '/poll'
    | '/poll/$id/analytics'
    | '/poll/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/poll/new'
    | '/poll/'
    | '/poll/$id/analytics'
    | '/poll/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PollNewRoute: typeof PollNewRoute
  PollIndexRoute: typeof PollIndexRoute
  PollIdAnalyticsRoute: typeof PollIdAnalyticsRoute
  PollIdIndexRoute: typeof PollIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/': {
      id: '/poll/'
      path: '/poll'
      fullPath: '/poll/'
      preLoaderRoute: typeof PollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/new': {
      id: '/poll/new'
      path: '/poll/new'
      fullPath: '/poll/new'
      preLoaderRoute: typeof PollNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$id/': {
      id: '/poll/$id/'
      path: '/poll/$id'
      fullPath: '/poll/$id/'
      preLoaderRoute: typeof PollIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$id/analytics': {
      id: '/poll/$id/analytics'
      path: '/poll/$id/analytics'
      fullPath: '/poll/$id/analytics'
      preLoaderRoute: typeof PollIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PollNewRoute: PollNewRoute,
  PollIndexRoute: PollIndexRoute,
  PollIdAnalyticsRoute: PollIdAnalyticsRoute,
  PollIdIndexRoute: PollIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
